Hardcode ex members urls
everypolitician-scrapers/malta-parliament pull request #1
Opened 2017-01-11 17:50 UTC by ondenman

Three members have left the legislature and are no long listed on the members page. Therefore, the scraper is no longer finding them.

However, the members' pages still exist.

2017-01-11 18:51 UTC, tmtmtmtm requested changes
This is a little bit too much extra complexity for an old-style scraper — especially one which can be switched to Scraped so simply.

I've migrated the underlying scraper, so suggest you reimplement these on top of that, which should hopefully be cleaner.

2017-01-12 11:42 UTC, tmtmtmtm requested changes
Can you get dates for these memberships, rather than injecting them in as if they're still active? If those aren't easily found, then we can live with it, but it would be good to add the dates if they are.

2017-01-12 11:42 UTC, tmtmtmtm commented on scraper.rb
> +    box.css('img/@src').first.text rescue nil
It's generally bad form to use exceptions for things that aren't actually exceptional. We abuse this from time to time, particularly in old-style scrapers where it makes the flow a lot easier. But one of the benefits of giving every field its own method is that we get to write things like this properly.

2017-01-12 11:42 UTC, tmtmtmtm commented on scraper.rb
> +).map do |url|
This is a bit ugly and difficult to follow. Assigning the list of members to scrape to a variable first should make this clearer and cleaner.

2017-03-02 12:48 UTC, ondenman commented
Closing in favour of adding `ExMemberPage`

2017-03-02 12:48 UTC, closed without merging