Scrape electoral history of ex members
everypolitician-scrapers/malta-parliament pull request #11
Opened 2017-01-31 10:52 UTC by ondenman

This is a step towards scraping electoral data of members. (everypolitician/everypolitician-data#24566).

The `:electoral_history` of ExMember objects is populated by electoral history dates structured as a hash. For example:

```
{"Tenth Parliament"=>
  {"Co-opted"=>"2004-05-24", "Oath of Allegiance"=>"2004-05-24", "Dissolution of Parliament"=>"2008-02-04"},
 "Eleventh Parliament"=>
  {"Elected on"=>"2008-03-12",
   "Oath of Allegiance as Parliamentary Secretary for Health"=>"2008-03-12",
   "Oath of Allegiance as Member"=>"2008-05-10",
   "Oath of Allegiance as Minister for Health, the Elderly and Community Care"=>"2010-02-10",
   "Ceased as Minister"=>"2013-03-09"},
 "Twelfth Parliament"=>
  {"Elected on"=>"2013-03-13", "Oath of Allegiance"=>"2013-04-06", "Resignation from Parliament"=>"2015-11-03"}}
```

2017-01-31 22:25 UTC, tmtmtmtm requested changes

2017-01-31 22:25 UTC, tmtmtmtm commented on test/ex_member_page_test.rb
> +require_relative '../lib/electoral_history'
you should really only be requiring things that the test itself is directly using. If you actually _do_ need to require these here, then something seems off.

2017-01-31 22:25 UTC, tmtmtmtm commented on test/ex_member_page_test.rb
> -  around { |test| VCR.use_cassette('GeorgeVella', &test) }
Why are you removing this test?

2017-01-31 22:25 UTC, tmtmtmtm commented on test/ex_member_page_test.rb
> +  end
this isn't really testing very much of what the PR claims to be adding. Let's talk in person about a better way of testing things like this.

2017-01-31 22:25 UTC, tmtmtmtm commented on lib/electoral_history.rb
> +  def to_h
Overriding the `to_h` method of a `Scraped::HTML` subclass seems wrong. Why do you need to do this?

2017-01-31 22:25 UTC, tmtmtmtm commented on lib/decorators/formatted_dates.rb
> +class FormattedDates < Scraped::Response::Decorator
I think you need to add some documentation here to explain what this Decorator is doing.

2017-02-06 12:19 UTC, ondenman commented
Addresses: https://github.com/everypolitician/everypolitician-data/issues/25279

2017-02-07 14:52 UTC, ondenman commented
Closing in favour of: https://github.com/everypolitician-scrapers/malta-parliament/pull/12

2017-02-07 14:52 UTC, closed without merging